version: '3.7'

services:
    web:
        container_name: eposhuk-backend-container
        image: xsakon/eposhuk-backend-image:latest
        hostname: eposhuk-backend-service
        build:
            context: .
        volumes:
          - ./logs:/app/logs
#        volumes:
#            - project-root:/var/www/html
#            - web_certs:/var/www/certs
#        networks:
#            default:
#                ipv4_address: 172.55.66.2
#        depends_on:
#            - kafdrop
