services:
    web:
        container_name: eposhuk-backend-container
        hostname: eposhuk-backend-service
        build:
            context: .
        volumes:
        - ./logs:/app/logs
        - /home/media:/home/media
        ports: 
        - '8000:8000'
#        networks:
#            default:
#                ipv4_address: 172.55.66.2
#        depends_on:
#            - kafdrop
