# Generated by Django 5.0.6 on 2024-05-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='latitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='longitude',
            field=models.DecimalField(decimal_places=50, max_digits=100),
        ),
    ]
