# Generated by Django 5.0.6 on 2024-05-11 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missingperson',
            name='last_seen_location',
        ),
        migrations.AddField(
            model_name='missingperson',
            name='last_seen_location',
            field=models.ManyToManyField(to='main.location'),
        ),
    ]
