# Generated by Django 5.0.6 on 2024-05-11 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_missingperson_last_seen_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missingpersonlocation',
            name='missing_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.missingperson'),
        ),
    ]
