name: Backend deploy to DigitalOcean

on:
  # push:
  #   branches: [backend]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    
    - name: Deploy to remote server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DIGITAL_OCEAN_HOST }}
        username: ${{ secrets.DIGITAL_OCEAN_USERNAME }}
        key: ${{ secrets.DIGITAL_OCEAN_SSH_PRIVATE_KEY }}
        passphrase: ${{ secrets.DIGITAL_OCEAN_SSH_PASSPHRASE }}
        script: |
          docker stop eposhuk-backend-container || true
          docker rm eposhuk-backend-container || true
          docker rmi -f eposhuk-backend-image || true
          git clone https://${{ secrets.GH_TOKEN }}@github.com/cyclozvir/hackathon2024.git .
          cd /home/hackathon2024/backend
          docker build -t eposhuk-backend-image -f Dockerfile .
          docker-compose -f docker-compose.yml up -d
